- id: terraform_docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  entry: hooks/terraform_docs.sh
  language: script
  files: (\.tf|\.terraform\.lock\.hcl)$
  exclude: \.terraform\/.*$
